### ISSUE TITLE
Not working with latest beta (1.1.34)

### ISSUE THREAD

**Issue by sandervs** [Zweikeks/saleae-logic-SimpleParallelNoClock-Analyzer#1]
Hi Zweikeks,

Unfortunately my new 16 channel pro only works with the newest saleae software which isn't  working with your analyzer, would it be possible to recompile it?

**Comment by Zweikeks** [comment]
Hello sandervs,

what exactly is not working?
My analyzer is based on Saleae Analyzer SDK 1.1.32. There hasn't been an update to this.
And there are only minor changes in the Logic Beta Releases 33 and 34.
So I don't know what to change in my code/compilation.

**Comment by sandervs** [comment]
Hi Zweikeks,

I think that the problem is that I run the 64bit version of the Saleae
software, I get an error when I start the program.

From release 1.1.34 onwards it is not possible anymore to install the 32
bit version on a 64 bit system.

Kind regards,
Sander van Schie

2015-05-17 10:24 GMT+02:00 Zweikeks notifications@github.com:

**Comment by Zweikeks** [comment]
Hello again,

I have built all the 4 combinations of x64, Win32, Debug and Release and you can download them here from GitHub. The 64 bit release version is in the directory x64\Release\SimpleParallelNoClock.dll.

Hope it works.

**Comment by sandervs** [comment]
Yes it is working, thanks a lot!

**Comment by sandervs** [comment]
I had missed that, sorry.

The plugin does actually work now :-)

Only minor issue that I have found is that I need to press "Edit settings"
of the analyzer and then save it in order to get the analyzer to decode the
parallel signals.

Sander

2015-05-21 17:01 GMT+02:00 Zweikeks notifications@github.com:
